### ISSUE TITLE
Tela de cadastro

### ISSUE THREAD

**Issue by etandel** [csestelo/lojaralho#9]
- [x] Criar model
- [x] Criar tela de cadastro
  - Banner
  - Formulario de cadastro
    - nome
    - email
    - confirmação de email
    - senha
    - confirmação de senha
    - endereço (opcional)
    - telefone opcional (opcional)
      - telegram / whatsapp / signal? (opcional)
    - foto (opcional)
  - botão de cadastro ("Cadastrar")
  - Botão para a home (no banner?)
- [x] Fazer botão de cadastro da home redirecionar para essa tela
- [x] Fazer banco guardar senha criptografada.
- [x] Deixar o email único.
- [x] Redirecionar para uma página 'bonita' qdo o cadastro for bem sucedido.
  - Testar:
    - [x] GET: view e template de welcome certos
- [x] Fazer testes:
  - [x] Validação do form de cadastro: confirmação de senha e email
  - [x] Form: email e username são únicos
  - [x] GET: template e view certos
  - [x] POST: Redirect para "welcome" quando cadastro é bem sucedido

**Comment by csestelo** [comment]
Ainda não permitimos foto e add unique tbm para username.
